### ISSUE TITLE
Unable to start the network

### ISSUE THREAD

**Issue by mattfortech** [mattdean1/blockchain-supply-chain#2]
Hello,
Under the Run section, I am trying to start the network but I am running into difficulty. It looks like the bna is generated successfully, but then restarting Fabric fails? I am not sure:

> Written Business Network Definition Archive file to 
> 	Output file: ./composer/biswas.bna
> 
> Command succeeded
> 
> ./restartFabric.sh: line 1: docker-compose: command not found
> ./restartFabric.sh: line 2: docker-compose: command not found
> Error response from daemon: No such container: cli
> composer <command>
> 
> Commands:
>   composer archive <subcommand>      Composer archive command
>   composer card <subcommand>         Command for managing business network cards
>   composer generator <subcommand>    Composer generator command to convert a Business Network Definition to code
>   composer identity <subcommand>     Composer identity command
>   composer network <subcommand>      Composer network command
>   composer participant <subcommand>  Composer participant command
>   composer report                    Command for creating a report of the current Composer environment
>   composer transaction <subcommand>  Composer transaction command
> 
> Options:
>   --help         Show help  [boolean]
>   -v, --version  Show version number  [boolean]
> 
> Examples:
>   composer archive create
>   composer identity issue
>   composer network install
>   composer participant add
>   composer transaction submit
> 
> For more information on Hyperledger Composer: https://hyperledger.github.io/composer/
> 
> Unknown arguments: c, n, runtime, install
> composer <command>
> 
> Commands:
>   composer archive <subcommand>      Composer archive command
>   composer card <subcommand>         Command for managing business network cards
>   composer generator <subcommand>    Composer generator command to convert a Business Network Definition to code
>   composer identity <subcommand>     Composer identity command
>   composer network <subcommand>      Composer network command
>   composer participant <subcommand>  Composer participant command
>   composer report                    Command for creating a report of the current Composer environment
>   composer transaction <subcommand>  Composer transaction command
> 
> Options:
>   --help         Show help  [boolean]
>   -v, --version  Show version number  [boolean]
> 
> Examples:
>   composer archive create
>   composer identity issue
>   composer network install
>   composer participant add
>   composer transaction submit
> 
> For more information on Hyperledger Composer: https://hyperledger.github.io/composer/
> 
> Unknown arguments: c, n, runtime, install
> composer <command>
> 
> Commands:
>   composer archive <subcommand>      Composer archive command
>   composer card <subcommand>         Command for managing business network cards
>   composer generator <subcommand>    Composer generator command to convert a Business Network Definition to code
>   composer identity <subcommand>     Composer identity command
>   composer network <subcommand>      Composer network command
>   composer participant <subcommand>  Composer participant command
>   composer report                    Command for creating a report of the current Composer environment
>   composer transaction <subcommand>  Composer transaction command
> 
> Options:
>   --help         Show help  [boolean]
>   -v, --version  Show version number  [boolean]
> 
> Examples:
>   composer archive create
>   composer identity issue
>   composer network install
>   composer participant add
>   composer transaction submit
> 
> For more information on Hyperledger Composer: https://hyperledger.github.io/composer/
> 
> Unknown arguments: c, n, runtime, install
> composer <command>
> 
> Commands:
>   composer archive <subcommand>      Composer archive command
>   composer card <subcommand>         Command for managing business network cards
>   composer generator <subcommand>    Composer generator command to convert a Business Network Definition to code
>   composer identity <subcommand>     Composer identity command
>   composer network <subcommand>      Composer network command
>   composer participant <subcommand>  Composer participant command
>   composer report                    Command for creating a report of the current Composer environment
>   composer transaction <subcommand>  Composer transaction command
> 
> Options:
>   --help         Show help  [boolean]
>   -v, --version  Show version number  [boolean]
> 
> Examples:
>   composer archive create
>   composer identity issue
>   composer network install
>   composer participant add
>   composer transaction submit
> 
> For more information on Hyperledger Composer: https://hyperledger.github.io/composer/
> 
> Unknown arguments: c, n, runtime, install
> composer <command>
> 
> Commands:
>   composer archive <subcommand>      Composer archive command
>   composer card <subcommand>         Command for managing business network cards
>   composer generator <subcommand>    Composer generator command to convert a Business Network Definition to code
>   composer identity <subcommand>     Composer identity command
>   composer network <subcommand>      Composer network command
>   composer participant <subcommand>  Composer participant command
>   composer report                    Command for creating a report of the current Composer environment
>   composer transaction <subcommand>  Composer transaction command
> 
> Options:
>   --help         Show help  [boolean]
>   -v, --version  Show version number  [boolean]
> 
> Examples:
>   composer archive create
>   composer identity issue
>   composer network install
>   composer participant add
>   composer transaction submit
> 
> For more information on Hyperledger Composer: https://hyperledger.github.io/composer/
> 
> Unknown arguments: c, n, runtime, install
> composer network start [options]
> 
> Starts a specific version of a business network that is already installed to Hyperledger Fabric
> 
> Options:
>   --help                             Show help  [boolean]
>   -v, --version                      Show version number  [boolean]
>   --card, -c                         The cardname to use to start the network  [string] [required]
>   --networkName, -n                  Name of the business network to start  [required]
>   --networkVersion, -V               Version of the business network to start  [required]
>   --loglevel, -l                     The initial loglevel to set  [choices: "INFO", "WARNING", "ERROR", "DEBUG"]
>   --option, -o                       Options that are specific to connection. Multiple options are specified by repeating this option  [string]
>   --optionsFile, -O                  A file containing options that are specific to connection  [string]
>   --networkAdmin, -A                 The identity name of the business network administrator  [string] [required]
>   --networkAdminCertificateFile, -C  The certificate of the business network administrator  [string]
>   --networkAdminEnrollSecret, -S     The enrollment secret for the business network administrator  [string]
>   --file, -f                         File name of the card to be created  [string]
> 
> Missing required arguments: networkName, networkVersion
> Error: Error trying to ping. Error: No peers available to query. last error was Error: 14 UNAVAILABLE: Connect Failed
> Command failed
> 
> Error: Error trying to ping. Error: No peers available to query. last error was Error: 14 UNAVAILABLE: Connect Failed
> Command failed
> 
> Error: Error trying to ping. Error: No peers available to query. last error was Error: 14 UNAVAILABLE: Connect Failed
> Command failed
> 
> Error: Error trying to ping. Error: No peers available to query. last error was Error: 14 UNAVAILABLE: Connect Failed
> Command failed
> 
> Error: Error trying to ping. Error: No peers available to query. last error was Error: 14 UNAVAILABLE: Connect Failed
> Command failed
> 
> rm: cannot remove './grower-network-admin@biswas.card': No such file or directory
> rm: cannot remove './producer-network-admin@biswas.card': No such file or directory
> rm: cannot remove './filler-network-admin@biswas.card': No such file or directory
> rm: cannot remove './distributor-network-admin@biswas.card': No such file or directory
> rm: cannot remove './retailer-network-admin@biswas.card': No such file or directory

**Comment by nitishbharti** [comment]
I am also getting same issue. How did you solve that.

**Comment by trinayanbhatt** [comment]
Same problem with me too, I am not able to deploy the network.
